### ISSUE TITLE
templates for submission

### ISSUE THREAD

**Issue by chassenr** [gfbio/molecular-submission-templates#2]
I am in the process of filling in the full_template.csv

I think that in the gfbio wiki, sample is defined slightly differently than in ENA, and is referring to the generated sequence data, i.e. runs (or did I get this wrong?). I will therefore always indicate if I am talking about samples as defined in ENA (ENA) or how I understood the definition in the wiki (GFBIO)

In the full_template file all data refers to sequencing runs (ENA). However, all the MIxS information is referring to sample (ENA). This leads to a lot of repetitive data in the csv file. E.g. if different size fraction of the same sample (ENA) were sequenced, environmental information such as temperature, salinity, etc. would repeat. The same is the case if several sequencing runs were conducted for the same sample. Apart from this being kind of a pain for me right now reformatting the tables, I think that parameters that were only measured once should also only appear once in the dataset.

I would suggest to keep the samples (GFBIO) and mixs templates separate for the submission, as done in ENA. I am aware that if there are a differing number of entries in the sample and mixs files, the mapping of data of the 2 different files should be based on a unique sample (ENA) identifier that can however be repeated for different sequence files.

**Comment by ikostadi** [comment]
Hi Christiane,

thank you very much for your suggestion. We will review it and get back to you as soon as possible.

Best,
Ivo

**Comment by jzrapp** [comment]
Hi, 

I'm just filling in the template and stumble over the NCBI taxonomy ID. Not sure wheather tag sequences count as metagenomes? And also: for some of my samples there are well-defined categories, but for others I cannot find a good fit. Should I just refer to the highest rank I can break it down to? Like "Marine metagenome" although actually talking about sea ice algae samples...?

**Comment by jzrapp** [comment]
Hi again, 

what does "investigation type" and "environmental package" in the mixs table refer to? There is no info in the wiki.

**Comment by ikostadi** [comment]
Hi Josie,

please excuse the gaps in our documentation, we'll try to fill it in as quickly as possible (I added some explanation to the points you mentioned). I will try to answer your questions one by one. Please note that you can start a submission with only a basic set of infos (the mandatory fields from the sample template) and we will help you figure out the rest.

* Tag sequences do count as metagenomes. In this context, metagenomes is taken to mean 'community-based'.
* I would suggest to use the lowest (most comprehensive or exact) rank possible. You could assign different samples different TaxIDs. It will be easier to help you once I see the data.
* I included a short explanation for "investigation type" and "environmental package", but you can just take 'mimarks-survey' and 'water' (respectively) as values for those. If necessary, we can improve on that later on.


If you have all other mandatory columns set up, please contact me and I will give you access to a pre-release version of our new and improved submission system.

Looking forward to meeting you data!

Best,
Ivo

**Comment by jzrapp** [comment]
@ikostadi 
I'm ready to submit my filled-out template :)

Thanks for your help!

**Comment by chassenr** [comment]
@ikostadi I was just wondering if you had time to think about my suggestion to have 2 separate template, one for sequencing runs, and another for sample information with an identifier to link both that only needs to be unique for the sample sheet and not the sequencing runs?

**Comment by ikostadi** [comment]
@jzrapp, I just sent you the details on how to access the latest version of our submission system which will be available to the public from April 27th onwards.

@chassenr, we do like your suggestion! As you can see in the repository, we had two separate templates, one for the sequencing information [(sample_template.csv)](https://github.com/gfbio/molecular-submission-templates/blob/master/sample_template.csv) and one for the MIxS metadata (misx_template.csv)[https://github.com/gfbio/molecular-submission-templates/blob/master/mixs_template.csv] from the very beginning. The [full template](https://github.com/gfbio/molecular-submission-templates/blob/master/full_template.csv) which we currently recommend using was simply the easiest to support technically in the beginning. If you don't mind, I will close this issue and open a new, dedicated one for this improvement request (please be aware it will take some time and input from your/user side to get this done).
